version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: expense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
      MYSQL_USER: expense
      MYSQL_DATABASE: transactions
      MYSQL_PASSWORD: ExpenseApp@1
    networks:
      - expense
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  backend:
    image: siva9666/backend:1.0
    container_name: expense-backend
    environment:
      - DB_HOST=expense-mysql
    networks:
      - expense
    depends_on:
      - db
  frontend:
    image: siva9666/frontend:1.0
    container_name: expense-frontend
    ports:
      - "80:80"
    networks:
      - expense
    depends_on:
      - backend
        
networks:
  expense:
    driver: bridge

volumes:
  mysql_data:
