---
apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-db-initialization-script
data:
  init.d: |
    CREATE DATABASE IF NOT EXISTS transactions;
    USE transactions;

    CREATE TABLE IF NOT EXISTS transactions (
        id INT AUTO_INCREMENT PRIMARY KEY,
        amount INT,
        description VARCHAR(255)
    );

    CREATE USER IF NOT EXISTS 'expense'@'%' IDENTIFIED BY 'ExpenseApp@1';
    GRANT ALL ON transactions.* TO 'expense'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-database: transactions