apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: RW5wZW5zZUFwcEAx  # Base64 encoded 'ExpenseApp@1'
  mysql-user: ZXhwZW5zZQ==               # Base64 encoded 'expense'
  mysql-password: RW5wZW5zZUFwcEAx 